resolver: lts-13.19
packages:
- .
extra-deps:
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
- git: https://github.com/seagreen/replica.git
  commit: 22aae09614e6a17afc672f0bdba09225b715e829
- git: https://github.com/pkamenarsky/concur.git
  commit: dc5347b35c79654d58fa95716f425ee7248504fb
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
